#!/usr/bin/env ruby

ENV['PATH'] = [
  __dir__ + '/.venv/bin',
  '/opt/homebrew/bin',
  ENV['PATH']
].join(':')

template_name = ARGV.shift
input_filename = ARGV.shift
output_filename = ARGV.shift

system(
    '/opt/homebrew/bin/pandoc',

    '--wrap=none',

    '--pdf-engine',
    'weasyprint',

    '--lua-filter',
    __dir__ + '/filter-wordcount.lua',

    '--lua-filter',
    __dir__ + '/filter-footnote.lua',

    '--template',
    __dir__ + '/templates/' + template_name + '.html',

    '--output',
    output_filename,

    '--shift-heading-level-by=1',

    input_filename,
)
